"""initial schema - all 25 tables from docs/DATABASE_SCHEMA.md

Revision ID: 6df67b513256
Revises: 
Create Date: 2026-09-14 14:30:50.786491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6df67b513256'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Native Postgres ENUM types created implicitly by the sa.Enum() columns
# below. `op.drop_table()` does NOT drop these — they are independent
# database objects — so downgrade() must drop them explicitly, or a
# downgrade+upgrade cycle fails with "type already exists".
_ENUM_TYPE_NAMES = [
    "actor_type", "anchor_type", "approval_decision", "approval_type",
    "article_status", "blog_platform_status", "brief_status", "campaign_status",
    "gap_status", "gap_type", "generated_by", "internal_link_status",
    "job_status", "job_type", "keyword_source", "keyword_type", "llm_provider",
    "page_type", "pipeline_stage", "project_status", "prompt_agent_type",
    "publication_method", "publication_status", "rule_scope", "search_engine",
    "serp_source", "topic_status", "user_role",
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='blog_platform_status'), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_encrypted', sa.String(length=500), nullable=True),
    sa.Column('login_url', sa.String(length=1000), nullable=True),
    sa.Column('category_default', sa.String(length=255), nullable=True),
    sa.Column('last_publish_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_table', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('idea', 'brief', 'writing', 'audit', 'human_review', 'published', 'rejected', name='pipeline_stage'), nullable=False),
    sa.Column('from_status', sa.String(length=100), nullable=True),
    sa.Column('to_status', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('ai', 'user', name='actor_type'), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applicable_page_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_outline_skeleton', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_word_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('link_placement_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('global', 'project', 'campaign', name='rule_scope'), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=True),
    sa.Column('anchor_distribution', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('link_position_max_words', sa.Integer(), nullable=False),
    sa.Column('max_outbound_links', sa.Integer(), nullable=False),
    sa.Column('max_links_per_blog_per_month', sa.Integer(), nullable=True),
    sa.Column('min_days_between_links_same_target', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='project_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_table', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('approval_type', sa.Enum('topic_selection', 'brief_approval', 'pre_publish', name='approval_type'), nullable=False),
    sa.Column('decision', sa.Enum('approved', 'rejected', name='approval_decision'), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=1000), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_knowledge_base',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('brand_voice_tone', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('industry_context', sa.Text(), nullable=True),
    sa.Column('style_guidelines', sa.Text(), nullable=True),
    sa.Column('forbidden_words', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mandatory_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_reference_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('custom_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_type', sa.Enum('keyword_intel', 'topic_gen', 'competitor_analysis', 'brief_generation', 'article_write', 'seo_audit', 'internal_link_suggestion', name='prompt_agent_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('target_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('main_keyword', sa.String(length=500), nullable=False),
    sa.Column('page_type', sa.Enum('product', 'article', 'category', name='page_type'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('keyword_intel', 'topic_gen', 'article_write', 'seo_audit', 'publish', 'competitor_analysis', 'brief_generation', 'internal_link_suggestion', 'serp_fetch', name='job_type'), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='job_status'), nullable=False),
    sa.Column('provider', sa.Enum('openai', 'claude', name='llm_provider'), nullable=True),
    sa.Column('prompt_template_id', sa.Integer(), nullable=True),
    sa.Column('prompt_template_version', sa.Integer(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('anchor_text', sa.String(length=500), nullable=False),
    sa.Column('anchor_type', sa.Enum('exact', 'partial', 'semantic', 'brand', name='anchor_type'), nullable=False),
    sa.Column('usage_limit', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('total_links_target', sa.Integer(), nullable=False),
    sa.Column('blog_count', sa.Integer(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('planning', 'in_progress', 'completed', 'paused', name='campaign_status'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internal_link_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_target_page_id', sa.Integer(), nullable=False),
    sa.Column('destination_target_page_id', sa.Integer(), nullable=False),
    sa.Column('suggested_anchor', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'applied', 'dismissed', name='internal_link_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['destination_target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('type', sa.Enum('main', 'related', 'semantic', name='keyword_type'), nullable=False),
    sa.Column('source', sa.Enum('ai', 'manual', name='keyword_source'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('serp_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=500), nullable=False),
    sa.Column('search_engine', sa.Enum('google', name='search_engine'), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.Enum('manual', 'api', name='serp_source'), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('competitor_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=True),
    sa.Column('source_serp_snapshot_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('fetched_title', sa.String(length=500), nullable=True),
    sa.Column('fetched_headings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_word_count', sa.Integer(), nullable=True),
    sa.Column('top_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_serp_snapshot_id'], ['serp_snapshots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('suggested', 'selected', 'rejected', name='topic_status'), nullable=False),
    sa.Column('generated_by', sa.Enum('ai', 'manual', name='generated_by'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_briefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('content_template_id', sa.Integer(), nullable=True),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('outline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_word_count', sa.Integer(), nullable=False),
    sa.Column('keywords_to_include', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('must_include_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tone', sa.String(length=500), nullable=True),
    sa.Column('source_content_gap_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', name='brief_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_template_id'], ['content_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('content_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('gap_topic', sa.String(length=500), nullable=False),
    sa.Column('gap_type', sa.Enum('topic', 'keyword', 'heading', name='gap_type'), nullable=False),
    sa.Column('source_competitor_page_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('new', 'used_in_topic', 'ignored', name='gap_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_competitor_page_id'], ['competitor_pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('content_brief_id', sa.Integer(), nullable=True),
    sa.Column('target_page_id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('blog_platform_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_audit', 'reviewed', 'needs_human_review', 'approved', 'published', 'rejected', name='article_status'), nullable=False),
    sa.Column('human_approved', sa.Boolean(), nullable=False),
    sa.Column('human_approved_by', sa.Integer(), nullable=True),
    sa.Column('human_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ),
    sa.ForeignKeyConstraint(['blog_platform_id'], ['blog_platforms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_brief_id'], ['content_briefs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['human_approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_page_id'], ['target_pages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anchor_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anchor_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('anchor_type', sa.Enum('exact', 'partial', 'semantic', 'brand', name='anchor_type'), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['anchor_id'], ['anchors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('blog_platform_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.Enum('manual', 'automated', name='publication_method'), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', name='publication_status'), nullable=False),
    sa.Column('published_url', sa.String(length=1000), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blog_platform_id'], ['blog_platforms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seo_audit_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('check_name', sa.String(length=255), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seo_audit_results')
    op.drop_table('publications')
    op.drop_table('anchor_usage_log')
    op.drop_table('articles')
    op.drop_table('content_gaps')
    op.drop_table('content_briefs')
    op.drop_table('topics')
    op.drop_table('competitor_pages')
    op.drop_table('serp_snapshots')
    op.drop_table('keywords')
    op.drop_table('internal_link_suggestions')
    op.drop_table('campaigns')
    op.drop_table('anchors')
    op.drop_table('ai_jobs')
    op.drop_table('target_pages')
    op.drop_table('prompt_templates')
    op.drop_table('project_knowledge_base')
    op.drop_table('competitors')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('link_placement_rules')
    op.drop_table('content_templates')
    op.drop_table('content_status_history')
    op.drop_table('blog_platforms')
    # ### end Alembic commands ###

    bind = op.get_bind()
    for type_name in _ENUM_TYPE_NAMES:
        sa.Enum(name=type_name).drop(bind, checkfirst=True)
