"""add articles.audit_retry_count for SEO Audit retry loop

Revision ID: c66fb88c10c2
Revises: 6df67b513256
Create Date: 2026-09-30 10:39:57.204365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66fb88c10c2'
down_revision: Union[str, None] = '6df67b513256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default added by hand (autogenerate omits it): without one,
    # this fails outright on any environment with existing rows in
    # `articles`, since NOT NULL + no default has nothing to backfill with.
    op.add_column(
        'articles',
        sa.Column('audit_retry_count', sa.Integer(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'audit_retry_count')
    # ### end Alembic commands ###
